---
wandb_version: 1

_wandb:
    desc:
    value:
        cli_version: 0.13.11
        is_jupyter_run: false
        is_kaggle_kernel: false
        python_version: 3.8.16
        start_time: 1678292828.103179
        t:
            1:
                - 55
            2:
                - 55
            3:
                - 16
                - 23
            4: 3.8.16
            5: 0.13.11
            8:
                - 5
architecture:
    desc:
    value: CNN
dataset:
    desc:
    value: CIFAR-100
epochs:
    desc:
    value: 10
learning_rate:
    desc:
    value: 0.02
