---
wandb_version: 1

_name_or_path:
    desc:
    value: EleutherAI/pythia-70m-deduped
_wandb:
    desc:
    value:
        cli_version: 0.13.11
        framework: huggingface
        huggingface_version: 4.26.1
        is_jupyter_run: false
        is_kaggle_kernel: false
        m:
            - 1: train/global_step
              6:
                  - 3
            - 1: eval/loss
              5: 1
              6:
                  - 1
            - 1: eval/runtime
              5: 1
              6:
                  - 1
            - 1: eval/samples_per_second
              5: 1
              6:
                  - 1
            - 1: eval/steps_per_second
              5: 1
              6:
                  - 1
            - 1: train/epoch
              5: 1
              6:
                  - 1
            - 1: train/train_runtime
              5: 1
              6:
                  - 1
            - 1: train/train_samples_per_second
              5: 1
              6:
                  - 1
            - 1: train/train_steps_per_second
              5: 1
              6:
                  - 1
            - 1: train/total_flos
              5: 1
              6:
                  - 1
            - 1: train/train_loss
              5: 1
              6:
                  - 1
        python_version: 3.8.16
        start_time: 1678294433.875939
        t:
            1:
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
            2:
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
            3:
                - 7
                - 13
                - 16
                - 23
            4: 3.8.16
            5: 0.13.11
            6: 4.26.1
            8:
                - 5
adafactor:
    desc:
    value: false
adam_beta1:
    desc:
    value: 0.9
adam_beta2:
    desc:
    value: 0.999
adam_epsilon:
    desc:
    value: 1.0e-08
add_cross_attention:
    desc:
    value: false
architectures:
    desc:
    value:
        - GPTNeoXForCausalLM
auto_find_batch_size:
    desc:
    value: false
bad_words_ids:
    desc:
    value:
begin_suppress_tokens:
    desc:
    value:
bf16:
    desc:
    value: false
bf16_full_eval:
    desc:
    value: false
bos_token_id:
    desc:
    value: 0
chunk_size_feed_forward:
    desc:
    value: 0
cross_attention_hidden_size:
    desc:
    value:
data:
    desc:
    value: datasets=['boolq', 'rotten_tomatoes'] subsample=True num_train_samples=25 num_val_samples=15 pad_to_multiple_of=64
data_seed:
    desc:
    value: None
dataloader_drop_last:
    desc:
    value: false
dataloader_num_workers:
    desc:
    value: 0
dataloader_pin_memory:
    desc:
    value: true
ddp_bucket_cap_mb:
    desc:
    value: None
ddp_find_unused_parameters:
    desc:
    value: None
ddp_timeout:
    desc:
    value: 1800
debug:
    desc:
    value: '[]'
decoder_start_token_id:
    desc:
    value:
deepspeed:
    desc:
    value: None
disable_tqdm:
    desc:
    value: false
diversity_penalty:
    desc:
    value: 0.0
do_eval:
    desc:
    value: true
do_predict:
    desc:
    value: false
do_sample:
    desc:
    value: false
do_train:
    desc:
    value: false
early_stopping:
    desc:
    value: false
encoder_no_repeat_ngram_size:
    desc:
    value: 0
eos_token_id:
    desc:
    value: 0
eval_accumulation_steps:
    desc:
    value: None
eval_batch_size:
    desc:
    value: 32
eval_delay:
    desc:
    value: 0
eval_steps:
    desc:
    value: None
evaluation_strategy:
    desc:
    value: epoch
exponential_decay_length_penalty:
    desc:
    value:
finetuning_task:
    desc:
    value:
forced_bos_token_id:
    desc:
    value:
forced_eos_token_id:
    desc:
    value:
fp16:
    desc:
    value: false
fp16_backend:
    desc:
    value: auto
fp16_full_eval:
    desc:
    value: false
fp16_opt_level:
    desc:
    value: O1
fsdp:
    desc:
    value: '[]'
fsdp_min_num_params:
    desc:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    desc:
    value: None
full_determinism:
    desc:
    value: false
gradient_accumulation_steps:
    desc:
    value: 1
gradient_checkpointing:
    desc:
    value: false
greater_is_better:
    desc:
    value: None
group_by_length:
    desc:
    value: false
half_precision_backend:
    desc:
    value: auto
hidden_act:
    desc:
    value: gelu
hidden_size:
    desc:
    value: 512
hub_model_id:
    desc:
    value: None
hub_private_repo:
    desc:
    value: false
hub_strategy:
    desc:
    value: every_save
hub_token:
    desc:
    value: <HUB_TOKEN>
id2label:
    desc:
    value:
        '0': LABEL_0
        '1': LABEL_1
ignore_data_skip:
    desc:
    value: false
include_inputs_for_metrics:
    desc:
    value: false
initializer_range:
    desc:
    value: 0.02
intermediate_size:
    desc:
    value: 2048
is_decoder:
    desc:
    value: false
is_encoder_decoder:
    desc:
    value: false
jit_mode_eval:
    desc:
    value: false
label2id:
    desc:
    value:
        LABEL_0: 0
        LABEL_1: 1
label_names:
    desc:
    value: None
label_smoothing_factor:
    desc:
    value: 0.0
layer_norm_eps:
    desc:
    value: 1.0e-05
learning_rate:
    desc:
    value: 0.0003
length_column_name:
    desc:
    value: length
length_penalty:
    desc:
    value: 1.0
load_best_model_at_end:
    desc:
    value: false
local_rank:
    desc:
    value: -1
log_level:
    desc:
    value: passive
log_level_replica:
    desc:
    value: passive
log_on_each_node:
    desc:
    value: true
logging_dir:
    desc:
    value: ./runs/Mar08_16-53-52_cube-5b94517a-ece7-4956-b81a-16ce7827e3c3-8c6f869f-7ns6v
logging_first_step:
    desc:
    value: false
logging_nan_inf_filter:
    desc:
    value: true
logging_steps:
    desc:
    value: 500
logging_strategy:
    desc:
    value: steps
lr_scheduler_type:
    desc:
    value: linear
max_grad_norm:
    desc:
    value: 1.0
max_length:
    desc:
    value: 20
max_position_embeddings:
    desc:
    value: 2048
max_steps:
    desc:
    value: -1
metric_for_best_model:
    desc:
    value: None
min_length:
    desc:
    value: 0
model:
    desc:
    value: base='GPTNeoXForCausalLM' name='EleutherAI/pythia-70m-deduped' revision='step3000'
model_type:
    desc:
    value: gpt_neox
mp_parameters:
    desc:
    value: ''
no_cuda:
    desc:
    value: false
no_repeat_ngram_size:
    desc:
    value: 0
num_attention_heads:
    desc:
    value: 8
num_beam_groups:
    desc:
    value: 1
num_beams:
    desc:
    value: 1
num_hidden_layers:
    desc:
    value: 6
num_return_sequences:
    desc:
    value: 1
num_train_epochs:
    desc:
    value: 2
optim:
    desc:
    value: adamw_hf
optim_args:
    desc:
    value: None
output_attentions:
    desc:
    value: false
output_dir:
    desc:
    value: .
output_hidden_states:
    desc:
    value: false
output_scores:
    desc:
    value: false
overwrite_output_dir:
    desc:
    value: false
pad_token_id:
    desc:
    value:
past_index:
    desc:
    value: -1
per_device_eval_batch_size:
    desc:
    value: 32
per_device_train_batch_size:
    desc:
    value: 32
per_gpu_eval_batch_size:
    desc:
    value: None
per_gpu_train_batch_size:
    desc:
    value: None
prediction_loss_only:
    desc:
    value: false
prefix:
    desc:
    value:
problem_type:
    desc:
    value:
prompt:
    desc:
    value: num_virtual_tokens=2 prompt_tuning_init_text=' '
pruned_heads:
    desc:
    value: {}
push_to_hub:
    desc:
    value: false
push_to_hub_model_id:
    desc:
    value: None
push_to_hub_organization:
    desc:
    value: None
push_to_hub_token:
    desc:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    desc:
    value: last
remove_invalid_values:
    desc:
    value: false
remove_unused_columns:
    desc:
    value: true
repetition_penalty:
    desc:
    value: 1.0
report_to:
    desc:
    value: "['wandb']"
resume_from_checkpoint:
    desc:
    value: None
return_dict:
    desc:
    value: true
return_dict_in_generate:
    desc:
    value: false
rotary_emb_base:
    desc:
    value: 10000
rotary_pct:
    desc:
    value: 0.25
run_name:
    desc:
    value: .
save_on_each_node:
    desc:
    value: false
save_steps:
    desc:
    value: 500
save_strategy:
    desc:
    value: steps
save_total_limit:
    desc:
    value: None
seed:
    desc:
    value: 42
sep_token_id:
    desc:
    value:
sharded_ddp:
    desc:
    value: '[]'
skip_memory_metrics:
    desc:
    value: true
suppress_tokens:
    desc:
    value:
task_specific_params:
    desc:
    value:
temperature:
    desc:
    value: 1.0
tf32:
    desc:
    value: None
tf_legacy_loss:
    desc:
    value: false
tie_encoder_decoder:
    desc:
    value: false
tie_word_embeddings:
    desc:
    value: false
tokenizer_class:
    desc:
    value:
top_k:
    desc:
    value: 50
top_p:
    desc:
    value: 1.0
torch_compile:
    desc:
    value: false
torch_compile_backend:
    desc:
    value: None
torch_compile_mode:
    desc:
    value: None
torch_dtype:
    desc:
    value: float16
torchdynamo:
    desc:
    value: None
torchscript:
    desc:
    value: false
tpu_metrics_debug:
    desc:
    value: false
tpu_num_cores:
    desc:
    value: None
train:
    desc:
    value: output_dir='.' epochs=2 learning_rate=0.0003 per_device_train_batch_size=32 per_device_eval_batch_size=32 is_wandb=True wandb_project='chemnlp'
        run_name='pipeline_test'
train_batch_size:
    desc:
    value: 32
transformers_version:
    desc:
    value: 4.26.1
typical_p:
    desc:
    value: 1.0
use_bfloat16:
    desc:
    value: false
use_cache:
    desc:
    value: true
use_ipex:
    desc:
    value: false
use_legacy_prediction_loop:
    desc:
    value: false
use_mps_device:
    desc:
    value: false
use_parallel_residual:
    desc:
    value: true
vocab_size:
    desc:
    value: 50304
warmup_ratio:
    desc:
    value: 0.0
warmup_steps:
    desc:
    value: 0
weight_decay:
    desc:
    value: 0.0
xpu_backend:
    desc:
    value: None
